package com.primus.springdynamodb.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "user")
public class User {

    private String UserId;

    @DynamoDBAttribute
    private String FirstName;

    @DynamoDBAttribute
    private String LastName;

    @DynamoDBAttribute
    private String email;

    @DynamoDBAttribute
    private Address Address;


    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getUserId() {
        return UserId;
    }

    public void setUserId(String userId) {
        UserId = userId;
    }

    public String getFirstName() {
        return FirstName;
    }

    public void setFirstName(String firstName) {
        FirstName = firstName;
    }

    public String getLastName() {
        return LastName;
    }

    public void setLastName(String lastName) {
        LastName = lastName;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public com.primus.springdynamodb.entity.Address getAddress() {
        return Address;
    }

    public void setAddress(com.primus.springdynamodb.entity.Address address) {
        Address = address;
    }
}
